# Generated by Django 5.0.3 on 2024-04-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='name',
            field=models.CharField(default='Anonymous', max_length=25),
        ),
    ]
